"""
Django settings for prod_sam_siteadmin_api project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import oracledb

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=ki0f9l$g5d0t(6*9hf6--cppnh2ze+8f!vm9)7ld!xixl^m4k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'qawebapp.salesandmarketing.ai',
    'qawebapp2.salesandmarketing.ai',
    'qapywebapp.salesandmarketing.ai',
    'webapp.salesandmarketing.ai',
    'apilb.salesandmarketing.ai',
    'samsa.salesandmarketing.ai',
    'qasa.salesandmarketing.ai',
    '127.0.0.1',
    'localhost'
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'common_app',
    'auth_app',
    'affiliate_program_app',
    'analytics_app',
    'dashboard_app',  # Added for Dashboard module migration
    'smtp_app',  # Added for SMTP module migration
    'subaccount_pages_app',  # Added for Subaccount Pages module migration
    'freetemplate_app',  # Added for Free Template module migration
    'accounting_app',  # Added for Invoice, Billing, and Gateway migration
    'customer_app',  # Added for Contacts module migration
    'generalsections_app',  # Added for General Sections and Site Settings migration
    'emailCampaigns_app',  # Added for Email Campaign module migration
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'prod_sam_siteadmin_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'prod_sam_siteadmin_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
oracledb.init_oracle_client(lib_dir='/usr/lib/oracle/23/client64/lib')
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'prod',
#         'USER': 'root',
#         'PASSWORD': '01Samai007!',
#         'HOST': '10.0.128.96',
#         'PORT': '3306',
#         'OPTIONS': {
#             'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
#             'charset': 'utf8mb4',
#         }
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.oracle',
        'NAME': '10.0.130.233:1521/qa.salesandmarketing.ai',
        'USER': 'samai',
        'PASSWORD': '9L5OE70d+W33<s8?Aq,$',
    }
}

# MongoDB Configuration
MONGODB_SETTINGS = {
    'uri': 'mongodb://samai_production:ProdSamai%40007!@mongodb01.salesandmarketing.ai:27017/?authSource=prod_sam_ai_analytics',
    'database': 'prod_sam_ai_analytics'
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
}

# CORS settings
CORS_ALLOW_ALL_ORIGINS = True

# JWT Secret Key from application-prod.properties
JWT_SECRET_KEY = '462D4A614E645267556B58703273357638782F413F4428472B4B625065536856'

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.office365.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'support@salesandmarketing.ai'
EMAIL_HOST_PASSWORD = '!01Sup@SamAi@2025!'
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
DEFAULT_FROM_EMAIL = 'Support <support@salesandmarketing.ai>'

# Custom Constants
MAIN_WEB_APP_URL = 'https://webapp.salesandmarketing.ai/'
SITEURL = 'https://samsa.salesandmarketing.ai/'
SITEURLBACKEND = 'https://samsaapi.salesandmarketing.ai/v1/'

# Storage Paths
ABSOLUTE_SITE_URL = Path('/qa_samai_webapp_server/webroot/sa.salesandmarketing.ai/')
CSVSTORE_UPLOAD_DIR = ABSOLUTE_SITE_URL / 'csv_store/'
CSVDOWNLOAD_DIR = ABSOLUTE_SITE_URL / 'csv_download/'
PDFSAVE_UPLOAD_DIR = ABSOLUTE_SITE_URL / 'pdfsave/'

# Authorize.Net payment gateway info
ENVSYS = 'qaapi'
AUTHORIZENET_LOGIN_ID = '8F35vjvYt'
AUTHORIZENET_TRANSACTION_KEY = '3sewR75M52Ddg85N'
AUTHORIZENET_PRODUCTION_LOGIN_ID = '2ZQ6Tb85nq4R'
AUTHORIZENET_PRODUCTION_TRANSACTION_KEY = '5PB8m4gtwEB949gq'
COMPANY_NAME = 'SAM'
SITENAME = 'SAM'



